In [1]:
#sort searching counting function

In [2]:
#it is used in machine learning

In [3]:
import numpy as np

In [5]:
arr=np.array([4,5,6,3,5])

In [7]:
np.sort(arr)#ascending

array([3, 4, 5, 5, 6])

In [10]:
np.searchsorted(arr,34)#in which this is gone 5

5

In [11]:
arr1=np.array([0,32,422,323,0,0,0])

In [12]:
#we have to find non zerp data

In [13]:
np.count_nonzero(arr1)

3

In [14]:
arr

array([4, 5, 6, 3, 5])

In [18]:
#we have to find data of 4

In [17]:
np.where(arr>4)#given index where the data is present

(array([1, 2, 4]),)

In [19]:
np.extract(arr>4,arr)#this give data

array([5, 6, 5])

In [20]:
#byte represnting

In [21]:
arr.byteswap()

array([288230376151711744, 360287970189639680, 432345564227567616,
       216172782113783808, 360287970189639680])

In [22]:
#numpy copies and viwes

In [23]:
arr#we know solo and deepcopy

array([4, 5, 6, 3, 5])

In [24]:
a=np.copy(arr)#deep copy means data avliable in different location,

In [27]:
b=arr.view()

In [33]:
b=arr#solocopy copy in same location

In [28]:
b

array([4, 5, 6, 3, 5])

In [37]:
arr

array([45,  5,  6,  3,  5])

In [38]:
b[0]=45

In [39]:
b

array([45,  5,  6,  3,  5])

In [40]:
arr

array([45,  5,  6,  3,  5])

In [41]:
#numpy matrix library

In [42]:
import numpy.matlib as nm

In [44]:
nm.zeros(5)#in this case generate matrix in numpy case generate array,matrix minimun dim is 2

matrix([[0., 0., 0., 0., 0.]])

In [47]:
nm.ones((3,4))#matrix is subclass of arr

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [48]:
nm.eye(5)#identy

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [49]:
#numpy linear algebra

In [50]:
arr1=np.random.randint([[2,3],[4,5]])

In [52]:
arr2=np.random.randint([[2,3],[4,5]])

In [53]:
np.dot(arr1,arr2)

array([[ 3,  4],
       [ 9, 12]])

In [55]:
arr1@arr2#same as above ,symbol avliable as a/well as function.

array([[ 3,  4],
       [ 9, 12]])