In [1]:
#numpy Array manipulation

In [5]:
import numpy as np

In [7]:
arr=np.random.randint(1,10,(3,4))

In [8]:
arr

array([[6, 9, 1, 6],
       [7, 9, 1, 8],
       [5, 5, 3, 4]])

In [9]:
#shape chane

In [10]:
arr.reshape(6,2)

array([[6, 9],
       [1, 6],
       [7, 9],
       [1, 8],
       [5, 5],
       [3, 4]])

In [11]:
arr.reshape(2,6)#multiple of 12.

array([[6, 9, 1, 6, 7, 9],
       [1, 8, 5, 5, 3, 4]])

In [12]:
arr.reshape(2,7)

ValueError: cannot reshape array of size 12 into shape (2,7)

In [13]:
#negative work becasue it think as 6
arr.reshape(2,-7)

array([[6, 9, 1, 6, 7, 9],
       [1, 8, 5, 5, 3, 4]])

In [14]:
arr.T#rotate 180

array([[6, 7, 5],
       [9, 9, 5],
       [1, 1, 3],
       [6, 8, 4]])

In [15]:
arr.flatten()#covert 2d into 1d

array([6, 9, 1, 6, 7, 9, 1, 8, 5, 5, 3, 4])

In [17]:
arr1=np.array([1,2,3,4])

In [18]:
arr1.ndim

1

In [19]:
np.expand_dims(arr1,axis=1)#axis 1 means coulms ,changein 2d.

array([[1],
       [2],
       [3],
       [4]])

In [20]:
np.expand_dims(arr1,axis=0)

array([[1, 2, 3, 4]])

In [21]:
np.squeeze(arr)#nothing happen

array([[6, 9, 1, 6],
       [7, 9, 1, 8],
       [5, 5, 3, 4]])

In [22]:
data=np.array([[1],[2],[3]])

In [23]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.squeeze(data)#covert 1d from 2d but element is only one in ,above example is does not happen because elemnt is more than1 .

array([1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 4])

In [26]:
np.repeat(arr1,3)#3 time repeat

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [28]:
np.roll(arr1,shift=3) #shift/roll by 2.

array([2, 3, 4, 1])

In [29]:
np.diag(arr1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [30]:
#numpy binary operation

In [31]:
arr1=np.random.randint(1,10,(3,4))

In [32]:
arr2=np.random.randint(1,10,(3,4))

In [33]:
arr1

array([[4, 7, 2, 3],
       [1, 4, 3, 7],
       [7, 7, 8, 8]])

In [34]:
arr2

array([[9, 4, 5, 2],
       [2, 2, 3, 3],
       [6, 9, 6, 4]])

In [35]:
arr1+arr2#indexwise opration

array([[13, 11,  7,  5],
       [ 3,  6,  6, 10],
       [13, 16, 14, 12]])

In [36]:
arr1*arr2

array([[36, 28, 10,  6],
       [ 2,  8,  9, 21],
       [42, 63, 48, 32]])

In [37]:
arr1/arr2

array([[0.44444444, 1.75      , 0.4       , 1.5       ],
       [0.5       , 2.        , 1.        , 2.33333333],
       [1.16666667, 0.77777778, 1.33333333, 2.        ]])

In [38]:
arr1-arr2

array([[-5,  3, -3,  1],
       [-1,  2,  0,  4],
       [ 1, -2,  2,  4]])

In [39]:
arr1%arr2#reminder 

array([[4, 3, 2, 1],
       [1, 0, 0, 1],
       [1, 7, 2, 0]])

In [41]:
arr1 **arr2#power

array([[  262144,     2401,       32,        9],
       [       1,       16,       27,      343],
       [  117649, 40353607,   262144,     4096]])

In [42]:
arr1&arr2#anding

array([[0, 4, 0, 2],
       [0, 0, 3, 3],
       [6, 1, 0, 0]])

In [44]:
~arr1#negation

array([[-5, -8, -3, -4],
       [-2, -5, -4, -8],
       [-8, -8, -9, -9]])

In [45]:
arr1|arr2#oring

array([[13,  7,  7,  3],
       [ 3,  6,  3,  7],
       [ 7, 15, 14, 12]])

In [46]:
arr1>arr2#if yes then true

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [ True, False,  True,  True]])

In [47]:
#numpy string function

In [49]:
arr=np.array(['sart','ghodmare'])

In [50]:
arr

array(['sart', 'ghodmare'], dtype='<U8')

In [51]:
#uppercase
np.char.upper(arr)

array(['SART', 'GHODMARE'], dtype='<U8')

In [52]:
np.char.title(arr)

array(['Sart', 'Ghodmare'], dtype='<U8')

In [53]:
np.char.capitalize(arr)

array(['Sart', 'Ghodmare'], dtype='<U8')

In [54]:
#numpy mathematical function

In [55]:
arr1

array([[4, 7, 2, 3],
       [1, 4, 3, 7],
       [7, 7, 8, 8]])

In [56]:
np.sin(arr1)

array([[-0.7568025 ,  0.6569866 ,  0.90929743,  0.14112001],
       [ 0.84147098, -0.7568025 ,  0.14112001,  0.6569866 ],
       [ 0.6569866 ,  0.6569866 ,  0.98935825,  0.98935825]])

In [57]:
np.cos(arr1)

array([[-0.65364362,  0.75390225, -0.41614684, -0.9899925 ],
       [ 0.54030231, -0.65364362, -0.9899925 ,  0.75390225],
       [ 0.75390225,  0.75390225, -0.14550003, -0.14550003]])

In [59]:
np.tan(arr1)

array([[ 1.15782128,  0.87144798, -2.18503986, -0.14254654],
       [ 1.55740772,  1.15782128, -0.14254654,  0.87144798],
       [ 0.87144798,  0.87144798, -6.79971146, -6.79971146]])

In [60]:
np.log(arr1)

array([[1.38629436, 1.94591015, 0.69314718, 1.09861229],
       [0.        , 1.38629436, 1.09861229, 1.94591015],
       [1.94591015, 1.94591015, 2.07944154, 2.07944154]])

In [61]:
np.exp(arr1)

array([[5.45981500e+01, 1.09663316e+03, 7.38905610e+00, 2.00855369e+01],
       [2.71828183e+00, 5.45981500e+01, 2.00855369e+01, 1.09663316e+03],
       [1.09663316e+03, 1.09663316e+03, 2.98095799e+03, 2.98095799e+03]])

In [62]:
np.sqrt(arr1)

array([[2.        , 2.64575131, 1.41421356, 1.73205081],
       [1.        , 2.        , 1.73205081, 2.64575131],
       [2.64575131, 2.64575131, 2.82842712, 2.82842712]])

In [63]:
np.power(arr1,2)

array([[16, 49,  4,  9],
       [ 1, 16,  9, 49],
       [49, 49, 64, 64]])

In [64]:
np.mean(arr1)

5.083333333333333

In [66]:
np.median(arr1)

5.5

In [67]:
np.std(arr1)

2.3964673074247345

In [68]:
np.var(arr1)

5.743055555555556

In [69]:
np.min(arr1)

1

In [70]:
np.max(arr1)

8