In [1]:
#in python for numerical operation before there is no library avliable,whic ever bigdata,machinelearnig,nlp whatever is have array and matrix/numerical data then we use numpy.

In [2]:
import numpy as np

In [3]:
l=[1,2,3,4]#basic data structure we want to convert in array

In [5]:
ar=np.array(l)#array is differnrt data structure avliable in numpy

In [6]:
type(ar)

numpy.ndarray

In [7]:
#what is ndarry basically we get data in 1 dimension,2 dimensinon and so on,by using ndarry  we can represt any dimesnion array,rgb is a3 dimensional aaray.

In [8]:
np.array([[1,2,3],[34,5,6#2 dimesional aary ,for 1 dimeansionl we require only x axis and for 2 dimen x and y both.coordinate.max to max we can represt 3d data.

array([[ 1,  2,  3],
       [34,  5,  6]])

In [9]:
np.asarray(l)#it also conver it ndarry

array([1, 2, 3, 4])

In [11]:
type(np.asarray(l))

numpy.ndarray

In [12]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [13]:
type(np.asanyarray(l))

numpy.ndarray

In [14]:
#matrix by default 2 dimensional,it is a subset of array
b=np.matrix(l)

In [15]:
b

matrix([[1, 2, 3, 4]])

In [16]:
np.asanyarray(b)#it does not convert in array,becuasw asanyarray only convert array matrix is subst,because it is a arry form.

matrix([[1, 2, 3, 4]])

In [17]:
a=np.array(l)

In [18]:
a

array([1, 2, 3, 4])

In [19]:
c=a

In [20]:
c

array([1, 2, 3, 4])

In [21]:
a


array([1, 2, 3, 4])

In [22]:
c[0]=100

In [23]:
c#it is a solcopy because both data is one and store in same locatoion,same  place copy any varible can manipulates.

array([100,   2,   3,   4])

In [24]:
a

array([100,   2,   3,   4])

In [26]:
d=np.copy(a)#it is a deepcopy,above is solocopy

In [27]:
d

array([100,   2,   3,   4])

In [28]:
a

array([100,   2,   3,   4])

In [29]:
a[1]=400

In [30]:
a

array([100, 400,   3,   4])

In [31]:
#it does not completely copy becuase it data use different location.d copy a data in different location ,it does not copy in same location ,that why output is  not same.

array([100,   2,   3,   4])

In [ ]:
#numpy has differnet function used to genrate arrays

In [32]:
np.fromfunction(lambda i,j:i==j,(3,3))#using lambda crete 3 cross 3 data.i=row and j =colums 

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [40]:
#iteable varible
itrable=(i*i for i in range(5))
    

In [42]:
np.fromiter(itrable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [45]:
np.fromstring('234 423' ,sep=" ")

array([234., 423.])

In [46]:
np.fromstring('234 ,423' ,sep=" ,")

array([234., 423.])

In [47]:
#numpy datatype


In [48]:
l=[1,2,3,4]

In [49]:
a=np.array(l)

In [50]:
a

array([1, 2, 3, 4])

In [51]:
ar.ndim

1

In [54]:
ar2=np.array([[1,2,33,4],[1,2,3,4]])

In [55]:
ar2


array([[ 1,  2, 33,  4],
       [ 1,  2,  3,  4]])

In [56]:
ar2.ndim#checing the dim

2

In [57]:
a.size

4

In [58]:
ar2.size

8

In [59]:
a.shape

(4,)

In [60]:
ar2.shape

(2, 4)

In [61]:
a.dtype

dtype('int64')

In [62]:
ar2.dtype

dtype('int64')

In [65]:
ar22=np.array([(2.3,3,4),(3,5.3,6)])

In [66]:
ar22

array([[2.3, 3. , 4. ],
       [3. , 5.3, 6. ]])

In [68]:
ar22.dtype#because 1 data is float that why it change all

dtype('float64')

In [69]:
range(5)

range(0, 5)

In [70]:
list(range(5))#produce data in list

[0, 1, 2, 3, 4]

In [71]:

#We want float produced no because range always take int, 
list(range(3.5,4))

TypeError: 'float' object cannot be interpreted as an integer

In [72]:
#therfore numpy as provisiom for float point ,for range.
np.arange(2.3,5.6)#jump is 1

array([2.3, 3.3, 4.3, 5.3])

In [73]:
np.arange(2.3,5.6,0.3)#jump is 0.3

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [74]:
#we want arry to list
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [75]:
np.linspace(1,5,10)#10 data produce in betwween this ,means takes data betwwn 1 to 5 and and spaceline 10

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [76]:
np.zeros(5)#1 dim

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [82]:
np.zeros((3,5,2))#3 dim it has x,y,z axis

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [84]:
ar4=np.zeros((3,5,2,4))#0th fun

In [85]:
ar4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [86]:
ar4.ndim

4

In [87]:
#3d use in computervision deeplearing image is 3 d

In [88]:
np.ones(3)

array([1., 1., 1.])

In [89]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [91]:
on=np.ones((3,4,2))

In [92]:
on*5

array([[[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.],
        [5., 5.]]])

In [93]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [94]:
np.empty((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [95]:
np.eye(4)#identity matrix detriminat is 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [96]:
np.linspace(2,3,20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [97]:
np.logspace(2,4,10)#logarith

array([  100.        ,   166.81005372,   278.25594022,   464.15888336,
         774.26368268,  1291.54966501,  2154.43469003,  3593.8136638 ,
        5994.84250319, 10000.        ])

In [99]:
np.logspace(2,4,10,base=2)

array([ 4.        ,  4.66611616,  5.44316   ,  6.34960421,  7.4069977 ,
        8.64047791, 10.0793684 , 11.75787594, 13.71590373, 16.        ])

In [103]:
arr=np.random.randn(3,4)#random data here averag/meane =0 std=1 standard normal distrbution.

In [104]:
arr

array([[-0.59282371,  0.09182465,  0.22536592, -0.95876158],
       [-1.36872896,  0.32368381,  0.03793302, -1.00147656],
       [-0.89163189,  0.59462641,  0.87806985,  1.21653655]])

In [105]:
import pandas as pd
pd.DataFrame(arr)

0         1         2         3
0 -0.592824  0.091825  0.225366 -0.958762
1 -1.368729  0.323684  0.037933 -1.001477
2 -0.891632  0.594626  0.878070  1.216537

In [106]:
np.random.rand(3,4)#not standard normal distrbution.

array([[0.79934971, 0.10909746, 0.15827115, 0.19276175],
       [0.70439137, 0.89289585, 0.23251819, 0.20981637],
       [0.30236391, 0.98056374, 0.61241245, 0.30796309]])

In [109]:
arr1=np.random.randint(1,100,(3,4))#takes random data betwwen 1 and 100,3and4 is size and shape

In [110]:
import pandas as pd
pd.DataFrame(arr1)

0   1   2   3
0  52  88  29  23
1  57  11  32  13
2  22  52   6  25

In [114]:
pd.DataFrame(np.random.randint(1,100,(300,400))).to_csv('test.csv')#store in csv file.

In [113]:
arr=np.random.rand(3,4)#we want to change in another shape

In [115]:
arr

array([[-0.59282371,  0.09182465,  0.22536592, -0.95876158],
       [-1.36872896,  0.32368381,  0.03793302, -1.00147656],
       [-0.89163189,  0.59462641,  0.87806985,  1.21653655]])

In [116]:
arr.reshape(6,2)#multiple of above data menas 12 total multiple is 6,2

array([[-0.59282371,  0.09182465],
       [ 0.22536592, -0.95876158],
       [-1.36872896,  0.32368381],
       [ 0.03793302, -1.00147656],
       [-0.89163189,  0.59462641],
       [ 0.87806985,  1.21653655]])

In [117]:
arr.reshape(6,3)

ValueError: cannot reshape array of size 12 into shape (6,3)

In [118]:
#negative take beacuse it thigh negative as 2.
arr.reshape(6,-3)#it is use in image processing

array([[-0.59282371,  0.09182465],
       [ 0.22536592, -0.95876158],
       [-1.36872896,  0.32368381],
       [ 0.03793302, -1.00147656],
       [-0.89163189,  0.59462641],
       [ 0.87806985,  1.21653655]])

In [121]:
arr

array([[-0.59282371,  0.09182465,  0.22536592, -0.95876158],
       [-1.36872896,  0.32368381,  0.03793302, -1.00147656],
       [-0.89163189,  0.59462641,  0.87806985,  1.21653655]])

In [122]:
#slicing
arr[1]

array([-1.36872896,  0.32368381,  0.03793302, -1.00147656])

In [123]:
arr[1][1]

0.32368380602806657

In [124]:
arr[1:3]

array([[-1.36872896,  0.32368381,  0.03793302, -1.00147656],
       [-0.89163189,  0.59462641,  0.87806985,  1.21653655]])

In [127]:
arr[1:3,3]

array([-1.00147656,  1.21653655])

In [140]:
arr=np.random.randint(1,100,(5,5))

In [141]:
arr

array([[86, 20, 73, 31, 74],
       [94, 12, 83, 17,  5],
       [90,  9, 48,  5,  6],
       [58, 11, 82, 15, 95],
       [41, 31, 60, 20, 47]])

In [142]:
#we want only data>50
arr[arr>50]

array([86, 73, 74, 94, 83, 90, 58, 82, 95, 60])

In [143]:
arr

array([[86, 20, 73, 31, 74],
       [94, 12, 83, 17,  5],
       [90,  9, 48,  5,  6],
       [58, 11, 82, 15, 95],
       [41, 31, 60, 20, 47]])

In [144]:
arr[2:4]

array([[90,  9, 48,  5,  6],
       [58, 11, 82, 15, 95]])

In [147]:
arr[2:4,[1,2]]

array([[ 9, 48],
       [11, 82]])

In [148]:
arr[0][0]

86

In [149]:
#we can also manipuate at any time
arr[0][0]=344

In [150]:
arr

array([[344,  20,  73,  31,  74],
       [ 94,  12,  83,  17,   5],
       [ 90,   9,  48,   5,   6],
       [ 58,  11,  82,  15,  95],
       [ 41,  31,  60,  20,  47]])

In [151]:
arr


array([[344,  20,  73,  31,  74],
       [ 94,  12,  83,  17,   5],
       [ 90,   9,  48,   5,   6],
       [ 58,  11,  82,  15,  95],
       [ 41,  31,  60,  20,  47]])

In [152]:

arr1=np.random.randint(1,3,(3,3))  
arr2=np.random.randint(1,3,(3,3))  

In [153]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [154]:
arr2#index+index mapping

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [155]:
arr1+arr2

array([[3, 3, 2],
       [4, 3, 4],
       [2, 4, 3]])

In [156]:
arr1-arr2

array([[ 1,  1,  0],
       [ 0, -1,  0],
       [ 0,  0,  1]])

In [157]:
arr1/arr2

array([[2. , 2. , 1. ],
       [1. , 0.5, 1. ],
       [1. , 1. , 2. ]])

In [158]:
arr1*arr2#this is not standard matrix multiplcation it is indexwise

array([[2, 2, 1],
       [4, 2, 4],
       [1, 4, 2]])

In [159]:
arr1

array([[2, 2, 1],
       [2, 1, 2],
       [1, 2, 2]])

In [160]:
arr2

array([[1, 1, 1],
       [2, 2, 2],
       [1, 2, 1]])

In [161]:
#standar matrix multiplication is colum of 1st matrix and row of 2nd matrix 
arr1@arr2#standard matrix multiplication

array([[7, 8, 7],
       [6, 8, 6],
       [7, 9, 7]])

In [162]:
arr1/0#it is numpy

/tmp/ipykernel_147/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [163]:
arr1+100

array([[102, 102, 101],
       [102, 101, 102],
       [101, 102, 102]])

In [164]:
arr1**2

array([[4, 4, 1],
       [4, 1, 4],
       [1, 4, 4]])

In [165]:
#numpy broadcasting

In [167]:
arr=np.zeros((4,4))

In [168]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [169]:
row=np.array([1,2,3,4])

In [170]:
row

array([1, 2, 3, 4])

In [171]:
arr+row#it rowise addition , broadcasting change row value

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [172]:
#for coumn we have to use transpose.
row.T#it does not transpose because it is a 1d array

array([1, 2, 3, 4])

In [173]:
row.ndim

1

In [176]:
col=np.array([[1,2,3,4]])

In [177]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [178]:
col.T+arr#it columise addition , broadcasting change column value

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [180]:
arr1=np.random.randint(1,4,(3,4))

In [181]:
arr1

array([[2, 1, 3, 1],
       [1, 3, 2, 1],
       [2, 1, 1, 1]])

In [182]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.73205081, 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        , 1.        ]])

In [184]:
np.log10(arr1)

array([[0.30103   , 0.        , 0.47712125, 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.        ],
       [0.30103   , 0.        , 0.        , 0.        ]])

In [185]:
np.exp(arr1)

array([[ 7.3890561 ,  2.71828183, 20.08553692,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 ,  2.71828183],
       [ 7.3890561 ,  2.71828183,  2.71828183,  2.71828183]])

In [ ]:
#iamage is matrix /dimesnion